ifeq ($(TARGET_BOARD), )
  TARGET_BOARD = vcu118
  export TARGET_BOARD
endif

all:
	#$(Q)make -C dummy_net_blackhole
	$(Q)make -C dummy_net_dram
	#$(Q)make -C dummy_net_pktgen
	#$(Q)make -C dummy_net_loopback
	#$(Q)make -C rdma
	#$(Q)make -C memcached
